### ISSUE TITLE
Levenshtein Edit Distance Algorithm

### ISSUE THREAD

**Issue by normanhh3** [sethjuarez/numl#17]
It seems I keep running across the [Levenshtein Edit Distance algorithm](http://en.wikipedia.org/wiki/Levenshtein_distance).  In reviewing the code for this library I found other distance algorithms implemented, and wondered what might have caused this one to be left out.  (See Issue #16)

Given the importance of the algorithm and the relevance to information processing and loosely to machine learning, there are a few challenges to be considered.

Given a class: 

```
class SimilarWordEntry
{
    [Feature] public string WordA { get; set; }
    [Feature] public string WordB { get; set; }

    [Feature, LevenshteinDistance("WordA","WordB")] 
    public int EditDistance { get; set; }

    [Feature] public int WordALength { get { return WordA.Length; } }
    [Feature] public int WordBLength { get { return WordB.Length; } }

    // Where Soundex is computed following the guidelines at: http://en.wikipedia.org/wiki/Soundex
    [Feature, Soundex("WordA")] public string WordASoundex { get; set; }
    [Feature, Soundex("WordB")] public string WordBSoundex { get; set; }  

    [Label] public double SimilarityScore { get; set; }
}
```

With this syntax we can convert two input features into a third feature extracted by use of the algorithm.  The syntax is simply convenience over populating a Feature property with the result of the edit distance algorithm.

Thoughts?

**Comment by sethjuarez** [comment]
Awesome suggestion. It seems that this new aggregate feature would be useful under a number of different scenarios. I don't necessarily like the requirement of having a new property given that a regular or weak descriptor declaration would not need it at all. (See [descriptor docs](http://docs.numl.net/#Descriptors.html)). How would this look in the case of a strong descriptor? (given the aggregated property might not exist?)

**Comment by normanhh3** [comment]
Sorry I dropped off the face of the planet. :-/

The descriptor was definitely an area that was kind of throwing me as well.  :-/  I haven't spent enough time with that part of the code to have a good feel for how to "naturally" make it fit.

Seems like closing the issue at the moment seems best. :-/
