### ISSUE TITLE
LinearRegression- unable to load saved model

### ISSUE THREAD

**Issue by DashNY** [sethjuarez/numl#18]
I've found what appears to be a bug in LinearRegressionModel.Load/Save methods.
I get this error when loading a previously saved model.
Attached model and code to reproduce it - just run the code twice to repro the problem.

<pre>
Unhandled Exception: System.InvalidOperationException: There is an error in XML
document (18, 6). ---> System.InvalidOperationException: There is an error in XM
L document (18, 6). ---> System.InvalidOperationException: <e xmlns=''> was not
expected.
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderVector
.Read1_v()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, St
ring encodingStyle, XmlDeserializationEvents events)
   at numl.Utils.Xml.Read[T](XmlReader reader) in c:\projects\numl\numl\Utils\Xm
l.cs:line 152
   at numl.Supervised.Regression.LinearRegressionModel.ReadXml(XmlReader reader)
 in c:\projects\numl\numl\Supervised\Regression\LinearRegressionModel.cs:line 76

   at System.Xml.Serialization.XmlSerializationReader.ReadSerializable(IXmlSeria
lizable serializable, Boolean wrappedAny)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderLinear
RegressionModel.Read1_LinearRegressionModel()
</pre>

---CODE-----

```c#
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using numl;
using numl.Model;
using numl.Supervised;
using numl.Supervised.Regression;

namespace MachineLearningByFormulaDemo
{
    class Program
    {
        static void Main(string[] args)
        {
            // generate data to train our neural network
            var rnd = new Random();
            Func<double, double, double> func = (l, r) => l + 2 * r;


            IModel model;
            var data = new List<ModelItem>();
            const string modelFileName = "test.mdl";
            if (File.Exists(modelFileName))
            {
                model = new LinearRegressionModel().Load(modelFileName);
            }
            else
            {
                for (var i = 0; i < 100; i++)
                {
                    var left = rnd.NextDouble(0, 50000);
                    var right = rnd.NextDouble(0, 50000);
                    var result = func(left, right);
                    data.Add(new ModelItem { LeftOperand = left, RightOperand = right, Result = result });
                }
                var d = Descriptor.Create<ModelItem>();
                var g = new LinearRegressionGenerator { Descriptor = d };
                var learningModel = Learner.Learn(data, .80, 1000, g);
                model = learningModel.Model;
                model.Save(modelFileName);
            }

            // test our trained network with some sample data
            for (var i = 0; i < 10; i++)
            {
                var left = rnd.NextDouble(0, 50000);
                var right = rnd.NextDouble(0, 50000);
                var item = new ModelItem { LeftOperand = left, RightOperand = right /* Result will be predicted */};
                model.Predict(item);

                var predictedResult = item.Result;
                var expectedResult = func(left, right);
                var diff = Math.Abs(expectedResult - predictedResult) / expectedResult;
                Console.WriteLine("Expected: {0:N2}, Predicted: {1:N2}, Difference: {2:P}", expectedResult, item.Result, diff);
            }
        }
    }

    public class ModelItem
    {
        [Feature]
        public double LeftOperand { get; set; }
        [Feature]
        public double RightOperand { get; set; }
        [Label]
        public double Result { get; set; }
    }

    public static class RandomExtensions
    {
        public static double NextDouble(
            this Random random,
            double minValue,
            double maxValue)
        {
            return random.NextDouble() * (maxValue - minValue) + minValue;
        }
    }
}
```

**Comment by sethjuarez** [comment]
Gah! I will look into it. Thanks for the code.

**Comment by bdschrisk** [comment]
Issue found with underlying Vector serialization.  Issue occurs when Vector is not a root level element in the XML.

**Comment by DashNY** [comment]
Seth, have you ever considered replacing the usage of XmlSerializer with DataContractSerializer? I've heard it was a newer class and worked about 10 times faster. It also produces and consumes XML.
Let me know.

**Comment by sethjuarez** [comment]
Ugh... Serialization is a bit of a tricky issue. It basically sucks really. I have tried really hard to make sure the library does not take *any* dependencies but if I had it my way, I would just serialize everything to json. If I remember right, there was also a standard way to save certain models (but I can't find it right now).

**Comment by sethjuarez** [comment]
Ok - I remember now. It is called PMML: http://en.wikipedia.org/wiki/Predictive_Model_Markup_Language. Should we just support that?

**Comment by sethjuarez** [comment]
Fixed the bug - sorry for the delay! It turned out to be a weird descriptor serialization issue that I fixed across the board. Build 0.8.18 has kicked off and should be available soon.
