### ISSUE TITLE
Performance tweak in DecisionTreeGenerator.GetBestSplit

### ISSUE THREAD

**Issue by DashNY** [sethjuarez/numl#22]
Hi Seth,

I've run numl in the profiler that comes with Visual Studio and found this line of code to cause a lot of CPU utilization:
DecisionTreeGenerator.cs, line 212, inside GetBestSplit()
      **Activator.CreateInstance(ImpurityType);**

It's essentially a call to a costly Activator.CreateInstance from within a "for" loop. This could potentially be optimized by taking it out of the loop, or even calling it once and caching, if ImpurityType property is not meant to be assigned.

I'm not seeing any calls to the setter outside the DecisionTreeGenerator class, so it could potentially be made private, e.g.

public Type ImpurityType { get; private set; }

Thanks.

**Comment by sethjuarez** [comment]
Thanks for the find! Unfortunately a new instance of the ImpurityType is required per tree split as it contains information about the split that is utilized later up the stack. I have gone ahead and added a method to Ject that uses a cached compiled expression which should be a much faster approach to invoking the ctor on an arbitrary type. I saw significant gains (at least from the test runner) using this approach. I will push it up soon! 

Thanks for the find!
