### ISSUE TITLE
Deserialization error when using Load(STREAM)

### ISSUE THREAD

**Issue by DashNY** [sethjuarez/numl#26]
Hi Seth,

I'm getting an exception when trying to deserialize from a stream. Please check.
The error and the code are attached below

ERROR:
Unhandled Exception: System.InvalidOperationException: There is an error in XML
document (0, 0). ---> System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlTextReader.Read()
   at System.Xml.XmlReader.MoveToContent()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderDecisi
onTreeModel.Read1_DecisionTreeModel()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, St
ring encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(Stream stream)
   at numl.Supervised.Model.Load(Stream stream) in c:\projects\numl\numl\Supervi
sed\Model.cs:line 82
   at numl.Supervised.DecisionTree.DecisionTreeModel.Load(Stream stream) in c:\p
rojects\numl\numl\Supervised\DecisionTree\DecisionTreeModel.cs:line 72

    class Program
    {
        static void Main(string[] args)
        {
            var data = new List<MyData>();
            for (var i = 0; i < 1000; i++)
            {
                data.Add(new MyData { Prop1 = i, Prop2 = i + 1, Prop3 = i + 2, Result = i % 2 == 0 });
            }
            var d = Descriptor.Create<MyData>();
            var g = new DecisionTreeGenerator(d);
            g.SetHint(false);
            var learningModel = Learner.Learn(data, 0.80, 1000, g);
            Console.WriteLine(learningModel);

            string modelXml;
            using (var ms = new MemoryStream())
            {
                learningModel.Model.Save(ms);
                ms.Position = 0;
                using (var reader = new StreamReader(ms, Encoding.Unicode))
                {
                    modelXml = reader.ReadToEnd();
                }
            }

            // now read
            var m = new DecisionTreeModel();
            using (var stream = new MemoryStream())
            {
                using (var sr = new StreamWriter(stream, Encoding.Unicode))
                {
                    sr.Write(modelXml);
                    stream.Position = 0;
                    // THIS GIVES AN ERROR
                    m = (DecisionTreeModel)m.Load(stream);
                }
            }

        }
    }

    public class MyData
    {
        [Feature]
        public double Prop1 { get; set; }
        [Feature]
        public double Prop2 { get; set; }
        [Feature]
        public double Prop3 { get; set; }
        [Label]
        public bool Result { get; set; }
    }

**Comment by sethjuarez** [comment]
Uh oh - I will make sure to add a test for this to see what is going on.

**Comment by robink-teleopti** [comment]
Seems like the serialization is completely remodeled since this issue was created. But the answer is to leave out the Encoding.Unicode for the StreamReader / StreamWriter and it works. Probably time to close this issue.

**Comment by sethjuarez** [comment]
Yes - we've gone the way of json as opposed to xml. We are putting the finishing touches on it right now

**Comment by sethjuarez** [comment]
I will close this - it should work.
