### ISSUE TITLE
KNNModel serialization

### ISSUE THREAD

**Issue by pec92** [sethjuarez/numl#43]
Hi

when I serialize a KNNModel I get an exception on K.ToString("r").
If I change to K.ToString("d") it seems to work fine.

Could you help me, please?

'public override void WriteXml(XmlWriter writer)
{
            writer.WriteAttributeString("K", K.ToString("d"));
            Xml.Write<Descriptor>(writer, Descriptor);
            Xml.Write<Matrix>(writer, X);
            Xml.Write<Vector>(writer, Y);
}`

**Comment by bdschrisk** [comment]
Hey, depending on the build and platform you're running on, try using "G17" format instead of "r" or "d" to guarantee round-trips.

**Comment by pec92** [comment]
Hi, thanks for the hint! I changed "d" to "G17" and it works nicely.
Do I need to do a pull request or is better for me to use my local copy of numl ? (sorry for the nooby question)

**Comment by bdschrisk** [comment]
Use your local for now.  If you can replicate in the dev branch feel free to create a pull request :)

**Comment by sethjuarez** [comment]
This should work now
