### ISSUE TITLE
Guid property

### ISSUE THREAD

**Issue by robink-teleopti** [sethjuarez/numl#51]
I needed a guid property, and I implemented it for my solution. But I was thinking that maybe someone else might be interested in that. Should I prepare a PR for that? Or do you want to keep the core stuff as slim as possible?

**Comment by sethjuarez** [comment]
sure - why the addition?

**Comment by robink-teleopti** [comment]
We have a whole bunch objects with Guid identifiers from the database. With features and labels as Guid we can use those identifiers directly. Really neat for our use case so far.

**Comment by sethjuarez** [comment]
My sense is that a guid property would not be predictive enough to make a difference in any given model (I could be wrong....)

**Comment by bdschrisk** [comment]
Theoretically it would work the same way as a category type.  At prediction time we'd just map the output to a Guid, like we do with strings.

**Comment by robink-teleopti** [comment]
#52

**Comment by sethjuarez** [comment]
Yeah - totally get this now. Great idea - just merged a bit ago.
