### ISSUE TITLE
xproj can't load in my VS2015

### ISSUE THREAD

**Issue by davidqing2000** [sethjuarez/numl#59]
I try to download your project and open it in VS2015, I always get error, I can't open this project, do you have any guidance that can help me to open your projects? thanks.

**Comment by bdschrisk** [comment]
Let's see if we can help.  The xproj solution files will work with DotNet Core ([http://dot.net](url)) 1.0.0+ with VS2015.3.  There isn't any 3rd party dependencies to cause issues.  Can you paste the error here and we'll see if we can track down the cause?

**Comment by davidqing2000** [comment]
When I open your sln file, vs2015 show error- 'numl load failure;  numl.Tests load failure', my version is VS enterprise 2015 version 14.0.25420.01 Update 3.

**Comment by davidqing2000** [comment]
The portal version of numl can open in VS2015, but the version is not updated yet. When recompile this version, there are some missing file(e.g. CKmeans.cs, CoordinateDescents.cs,etc).

**Comment by bdschrisk** [comment]
The portable branch is currently in an archived state, the dev branch is the most up to date.  Can you confirm that you have the DotNetCore 1.0.1 Preview2 tooling installed?  If yes, can you delete the project.lock.json file and run a 'dotnet restore' and let us know how it works out?

**Comment by davidqing2000** [comment]
Thank you! I re-install the  DotNetCore 1.0.1 Preview2 tooling with X86 SDK, it works now.

**Comment by bdschrisk** [comment]
You're welcome.  If you have any questions on the project feel free to post them on [gitter.](https://gitter.im/sethjuarez/numl)
