### ISSUE TITLE
Model saving and loading

### ISSUE THREAD

**Issue by sethjuarez** [sethjuarez/numl#6]
Add ability to save and load models

**Comment by DashNY** [comment]
I was able to save a model into a file but I can't seem to figure out how to load it next time application starts.

SAVE:
                    learningModel = Learner.Learn(data, .80, 1000, generator);
                    learningModel.Model.Save(modelFileName);

LOAD: (not working, throwing NullRefException)
                    learningModel = new LearningModel();
                    learningModel.Model.Load(modelFileName);

**Comment by PippoAe** [comment]
I'm stuck on the same.
Saving works fine, but I don't know how to load it.

**Comment by rold2007** [comment]
@PippoAe I saw that recently @sethjuarez committed some code to better support serialization for NaiveBayes. Have you tried with the latest version ? Which generator did you use ? Have you seen [this issue](https://github.com/sethjuarez/numl/issues/74), it seems that after loading a model you still need to initialize the Descriptor.
If that doesn't solve your issue I would suggest you to open a new issue, including some code and steps to reproduce your issue.

**Comment by PippoAe** [comment]
Hi rold!
Thanks for the fast answer.
I now worked around the error.

I'm still using "model.Save(modelPath);" to save the TreeDecisionModel the learner has after learning.

To load I now use:
DecisionTreeModel model = (DecisionTreeModel)numl.Utils.Xml.Load(modelpath, typeof(DecisionTreeModel));

This returns me a working model again that I can use .Predict() on.

**Comment by sethjuarez** [comment]
Yay!!
