### ISSUE TITLE
LoadJson not implemented

### ISSUE THREAD

**Issue by SujataZ** [sethjuarez/numl#62]
I am using version 0.9.14-beta of nuget pkg for aspnetcore, and trying to load saved json of model. For DecisionTreeModel, the LoadJson method is not implemented. 
Any help?

**Comment by SujataZ** [comment]
Can anyone help on this please? 

I am trying to save model & then load it.
Tried using the other way of serializing as in the "tests" code, that gives error as 

Unable to cast object of type 'System.Collections.Generic.Dictionary`2[System.String,System.Object]' to type 'numl.Supervised.NaiveBayes.DecisionTreeModel'.

**Comment by SujataZ** [comment]
I got it working by saving in file only, instead of database.
"LoadJson" implementation would have been a great help to avoid all this coding.

**Comment by sethjuarez** [comment]
Sorry about that!! Excellent point. I will work on it. Thanks so much for the feedback.

**Comment by SujataZ** [comment]
Thanks, and this is a great machine learning library, looking forward to see more in it :)

**Comment by sethjuarez** [comment]
Also see 3414fb433ccf268c183abca78c0e06fa78c607fe for actual Json save and load code (along with supporting tests). This really needed to be fixed: thanks for the push! It should be up on nuget as build 0.9.15-beta.

**Comment by SujataZ** [comment]
Hey Seth, after upgrading to "0.9.15-beta", I do not see the method "LoadJson" on model, can you please help?

**Comment by sethjuarez** [comment]
Hi Sujata!
   It didn't make sense to put it on an instance of a model so I added it to the JsonReader class as a static method (see: https://github.com/sethjuarez/numl/blob/dev/Src/numl/Serialization/JsonReader.cs#L347-L352).
```csharp
var dt = JsonReader.ReadJson<DecisionTreeModel>(json);
```

**Comment by SujataZ** [comment]
Kudos Seth, it's working as expected now, 
thanks.
