### ISSUE TITLE
Please port to .NET Standard

### ISSUE THREAD

**Issue by DashNY** [sethjuarez/numl#65]
I'd love to use this library as part of a .NET Standard project, as well as .NET Core.
Thank you.

**Comment by sethjuarez** [comment]
Is it not already one? I think we target .NET Standard 1.3 if I remember right (I also may be completely off my rocker)

**Comment by DashNY** [comment]
Figured it out. Need to use "-Pre" to get the latest beta (0.9.15) version from Nuget.org<http://Nuget.org>. It doesn't show by default because it's a beta version.
Thanks.


On Mar 20, 2017, at 11:26 AM, Seth Juarez <notifications@github.com<mailto:notifications@github.com>> wrote:


Is it not already one? I think we target .NET Standard 1.3 if I remember right (I also may be completely off my rocker)
