### ISSUE TITLE
Datetime as label to learn - error "Dimensions do not match"

### ISSUE THREAD

**Issue by SujataZ** [sethjuarez/numl#68]
Hi Seth,

I am trying to set one integer as a feature & one datetime as the label for LinearRegression generator
I get error as "Dimensions do not match" for Learner.Learn method.

The training data passed is like 
{"Timestamp": "2016-06-06T15:49:46.6420000Z", "num1":32}

Below is the stacktrace -

   at numl.Math.LinearAlgebra.Vector.Dot(Vector one, Vector two)
   at numl.Supervised.Regression.LinearRegressionModel.Predict(Vector x)
   at numl.Learner.GenerateModel(IGenerator generator, Matrix x, Vector y, IEnumerable`1 examples, Double trainingPct, Int32 total)
   at numl.Learner.Learn(IEnumerable`1 examples, Double trainingPercentage, Int32 repeat, IGenerator generator)
   at MyLib.Repo.GenerateMyModel(List`1 trainingData)

Can you please help?

**Comment by bdschrisk** [comment]
Hi there,

Can you check that the training data has the same number of features as your input features at inference time - i.e. calling Predict().  This would be the case if you were including a new column not seen during training or possibly including the label when predicting.

Are you able to show the features from the Generator object?

**Comment by SujataZ** [comment]
I don't see any additional column added during training. The error is while training, not at predicting. 
Please see below code I am using, the exception is at the last part ("Error while generating model..")

LearningModel model = null;
            Descriptor descriptor = null;
            LinearRegressionGenerator generator = null;

            List<Dictionary<string, object>> data = new List<Dictionary<string, object>>();


            try
            {
                descriptor = Descriptor.New();

                descriptor.With("field1").As(typeof(Int32));

                descriptor.Learn("Timestamp").As(typeof(DateTime));
                descriptor.Label.Discrete = true;
            }
            catch (Exception ex)
            {
                Console.WriteLine("Error while generating the descriptor : " + ex.Message);
            }

            try
            {
                Dictionary<string, object> dataItem = new Dictionary<string, object>();

                dataItem.Add("Timestamp", DateTime.Parse("2016-06-06T15:46:11.0060000Z"));
                dataItem.Add("field1", 2);
                data.Add(dataItem);

                dataItem = new Dictionary<string, object>();
                dataItem.Add("Timestamp", DateTime.Parse("2016-06-06T15:49:46.6420000Z"));
                dataItem.Add("field1", 1);
                data.Add(dataItem);

                dataItem = new Dictionary<string, object>();
                dataItem.Add("Timestamp", DateTime.Parse("2016-06-06T15:50:14.9340000Z"));
                dataItem.Add("field1", 0);
                data.Add(dataItem);

            }
            catch (Exception ex)
            {
                Console.WriteLine("Error while constructing training data : " + ex.Message);
            }


            try
            {
                generator = new LinearRegressionGenerator()
                {
                    Descriptor = descriptor
                };
                model = Learner.Learn(data, 0.9, 50, generator);
            }
            catch (Exception ex)
            {
                Console.WriteLine("Error while generating model : " + ex.Message);
            }

**Comment by bdschrisk** [comment]
Using a DateTime feature as the label will throw an exception.  If you are doing timeseries forecasting you probably want to use the datetime as the feature (see [AsDateTime method](http://numl.net/api/numl.Model.DescriptorProperty.html#numl_Model_DescriptorProperty_AsDateTime_numl_Model_DatePortion_)) and the label as your value "field1".

**Comment by SujataZ** [comment]
Didn't know about AsDateTime... 

Tried the timeseries way by addinf field1 as label & time as feature earlier but the outcome was incorrect because I as not using AsDateTime... 

It's working now.

Thanks Chris.

**Comment by bdschrisk** [comment]
You're welcome.
