### ISSUE TITLE
How To Make A Prediction

### ISSUE THREAD

**Issue by pfdundar** [sethjuarez/numl#69]
I can create model successfully according to sample code. Now I should make a prediction with my unit data. How can I do this?

**Comment by pfdundar** [comment]
Ok, I found it. model.Predict(object o ) is used for this

**Comment by sethjuarez** [comment]
You can also do model.PredictValue(object o) if you just want the label prediction (and not have the system fill in the value). Sometimes the type cannot be written to so this call makes more sense.
