### ISSUE TITLE
How to load saved models?

### ISSUE THREAD

**Issue by hkcsser** [sethjuarez/numl#76]
After using 

> void Save(string file);

 to save the trained model, how to load the model again?

**Comment by sethjuarez** [comment]
Great question. This should help: https://github.com/sethjuarez/numl/blob/edc54b40e0cd56efa8011ce08cea6b4a0d682566/Src/numl.Tests/SerializationTests/BaseSerialization.cs#L54-L59

**Comment by hkcsser** [comment]
Thank you for your quick reply. I used the code above but it gave 

> System.TypeLoadException - Cannot find type Testing_ml.stats

 on `new JsonReader(f).Read();`.

**Comment by hkcsser** [comment]
I tried the data from /numl.Tests/Data/Iris.cs but it still gave` System.TypeLoadException-Cannot find type numl.Tests.Data.Iris` on `JsonReader.ReadJson`

>  var data = Iris.Load();
            var description = Descriptor.Create<Iris>();
            var generator = new DecisionTreeGenerator(50);
            var model = generator.Generate(description, data) as DecisionTreeModel;
            model.Save(AppDomain.CurrentDomain.BaseDirectory + "/model_cache/test.json");
            var learntmodel = JsonReader.ReadJson<DecisionTreeModel>(System.IO.File.ReadAllText(AppDomain.CurrentDomain.BaseDirectory + "/model_cache/test.json"));
