### ISSUE TITLE
Model load issue 

### ISSUE THREAD

**Issue by hkcsser** [sethjuarez/numl#77]
I tried to load a saved model but it gave` System.TypeLoadException-Cannot find type numl.Tests.Data.Iris` on `JsonReader.ReadJson`

>   var data = Iris.Load();
            var description = Descriptor.Create<Iris>();
            var generator = new DecisionTreeGenerator(50);
            var model = generator.Generate(description, data) as DecisionTreeModel;
            model.Save(AppDomain.CurrentDomain.BaseDirectory + "/model_cache/test.json");
            var learntmodel = JsonReader.ReadJson<DecisionTreeModel>(System.IO.File.ReadAllText(AppDomain.CurrentDomain.BaseDirectory + "/model_cache/test.json"));

**Comment by sethjuarez** [comment]
Looks like numl isn't aware of the type. Try making sure the assembly is registered:
```csharp
Register.Assembly(GetType().GetTypeInfo().Assembly);
```
Let me know if this works!

**Comment by hkcsser** [comment]
It works now! Thank you very much.

**Comment by sethjuarez** [comment]
Awesome!!!
